services:
  insurance.indt.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:80
      #- ASPNETCORE_HTTPS_PORTS=8081
      - ServiceBus:ServiceBusConnection=Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - MySqlDbcontext:ConnectionUrl=Server=dbMysql;Database=INDT;User ID=root;Password=admin;
      - DB_HOST=dbMysql 
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  dbMysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin # Replace with a strong password
      # MYSQL_DATABASE: your_database_name # Optional: a default database to create
      MYSQL_USER: admin # Optional: a user with superuser privileges
      # MYSQL_PASSWORD: admin # Optional: password for the user
    ports:
      - "3306:3306" # Maps host port 3306 to container port 3306
    volumes:
      - db_data:/var/lib/mysql # Persist data in a named volume
  emulator:
    container_name: "servicebus-emulator-compose"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "/Insurance.INDT.Application/ServiceBus/ConfigEmulator/Config.json"
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: sqledgeCompose
      MSSQL_SA_PASSWORD: "g0h0r5e8"  # Password should be same as what is set for SQL Edge  
      ACCEPT_EULA: 'Y'
      SQL_WAIT_INTERVAL: 15 # Optional: Time in seconds to wait for SQL to be ready (default is 15 seconds)
    depends_on:
      - sqledgeCompose
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqledgeCompose:
        container_name: "sqledge-compose"
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        networks:
          sb-emulator:
            aliases:
              - "sqledgeCompose"
        environment:
          ACCEPT_EULA: 'Y'
          MSSQL_SA_PASSWORD: "g0h0r5e8" # To be filled by user as per policy : https://learn.microsoft.com/en-us/sql/relational-databases/security/strong-passwords?view=sql-server-linux-ver16 

networks:
  sb-emulator:

volumes:
  db_data: