name: dbMysql-standalone
services:
   dbMysql-standalone:
    container_name: "dbMysql-standalone"
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin # Replace with a strong password
      # MYSQL_DATABASE: your_database_name # Optional: a default database to create
      MYSQL_USER: admin # Optional: a user with superuser privileges
      # MYSQL_PASSWORD: admin # Optional: password for the user
    ports:
      - "3306:3306" # Maps host port 3306 to container port 3306
    volumes:
      - db_data:/var/lib/mysql # Persist data in a named volume
volumes:
  db_data:      
